### ISSUE TITLE
How to add comics in theme

### ISSUE THREAD

**Issue by DeanDota** [jangrewe/cbreader#5]
Please how to add comics in theme ?

**Comment by jangrewe** [comment]
You put CBZ/CBR files into the folder you're referring to in the config file. This is supposed to be a companion app to Mylar, as mentioned in the README...

**Comment by DeanDota** [comment]
it stays that way and I can not read my comic https://i.imgur.com/igHh5UW.png

**Comment by jangrewe** [comment]
That looks like something breaks after reading the first comic. Please provide explicit error messages from your logs or webserver output, i can't help you without knowing what's actually wrong.

**Comment by DeanDota** [comment]
What's wrong with the script? I can not put comics. You have some version not bugged to send me.

**Comment by jangrewe** [comment]
It works for me. If it doesn't work for you, as mentioned before: give error messages. No error messages, no fixing.

**Comment by DeanDota** [comment]
he just can not read it and the whole bumpy picture appears on the cover image

**Comment by DeanDota** [comment]
in a way for me the whole theme is bugged https://i.imgur.com/Xxldeqk.png

**Comment by jangrewe** [comment]
That is not an error message. Does your PHP have the proper libraries, e.g. to read RAR and ZIP file, and ImageMagick to create images?
Again: i need an error message.
